### ISSUE TITLE
Move CDN to AWS, build up in terraform

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-assets#3]
Currently, we use digital-ocean spaces to serve as a CDN for this repo. There is a github action that (more or less) is able to make an exact copy of this repo and serve it up publicly (and without GH's rate limits) on a DigitalOcean space. @kepstein23  I think you have access to this - let me know if you don't, and would like to look at it.

I'd like to put everything on AWS, managed by Terraform if we can. I think (I don't know) that we'll end up using AWS cloudfront in the end. I don't really care about latency or internationalization/localization, it should just serve everything up the same regardless of where the participant is located, as cheaply as possible. 

Ideally, we'd have another terraform workspace for the CDN service, and when it is "up", it should either have a hook that looks for pushes to main in this repo, or should check periodically to make sure that it is synced. (preference for the former).

We may also end up creating a subdomain where the content is served, by creating a record on Route53 and directing it to the CDN. If that's required, we could use `cdn.deliberation-lab.org` or `assets.deliberation-lab.org`, whatever's your preference (is there a standard naming convention?).

At the moment, I'm happy for everything to be publicly available, but I'd like to know a little about what it would take to make users need a special key or link (that is unlisted and not google searchable) to access the content. 

Can you give me a brief synopsis of your recommended course of action in this issue, partly also for documentation, so we can look back on why we made the eventual decision?

**Comment by kepstein23** [comment]
I think cloudfront is the right service to use.  If we want everything on AWS, then I think we should set up this repo to deploy to an ec2 instance which is documented [here](https://docs.aws.amazon.com/codedeploy/latest/userguide/tutorials-github.html).  We can then use this ec2 instance as a server to set up the CDN in AWS as documented [here](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Introduction.html).  We could use s3 as an origin server instead.  I'm not really sure whether ec2 or s3 would be better to use as an origin server, but I think ec2 would make the CI easier and I was able to find more documentation for that, so it seems like the more popular choice.  We also have the option to use our own origin server, but given that the goal is to put everything in AWS, I think it makes sense to either use ec2 or s3.

I also think all of this could be done with terraform and GitHub actions.  We can provision the ec2 instance using terraform in deliberation-infrastructure, and we can set up a GitHub Action to deploy to it as documented [here](https://aws.amazon.com/blogs/devops/integrating-with-github-actions-ci-cd-pipeline-to-deploy-a-web-app-to-amazon-ec2/).  Then, we also can use terraform to set up the CDN, as is done [here](https://hands-on.cloud/cloudfront-terraform-examples/#h-integrating-cloudfront-with-ec2-using-terraform).  

Best practices for naming seem to be cdn.domain.org, but there doesn't seem to be a super strong opinion.

For restricting access, I think we can just use signed urls with cloudfront which is documented [here](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-urls.html)

**Comment by JamesPHoughton** [comment]
My first guess would be that S3 would be simpler as an origin server than EC2, as everything we will be serving here is just static assets. That's not based on experience so much as a gut feeling. If it's S3, we don't have to be responsible for an HTTP server, and all the overhead that entails. 

Another option to investigate is if the GH repo itself could be the origin server, with CloudFront mirroring that directly, such that we don't have to duplicate data anywhere. I haven't looked into it, is that possible?

One more option might be to ignore cloudfront and see if S3 on its own would be a valid server for static files. It probably wouldn't be as "fast" for the client as cloudfront, but might be acceptable for our needs.

- [ ] Lets do a bit more research before we commit to a solution - maybe list the major options in this issue thread, and write out pros/cons in terms of cost, user performance (in terms of actual latency - how bad is the worst option, from a practical perspective) complexity to set up, and difficulty of maintaining/keeping up to date.

> Best practices for naming seem to be cdn.domain.org

Works for me!

> For restricting access, I think we can just use signed urls with cloudfront which is documented [here](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-urls.html)

Great. Lets not bother for now, but good to have in mind.

**Comment by kepstein23** [comment]
The four main options seem to be: S3 on its own, GitHub on its own, EC2 with cloudfront, and S3 with cloudfront.

### S3 by itself

**Pro**
- S3 on its own is fine for static sites
- Can use custom domain with Route53
- Don't need to use/learn cloudfront
**Con**
- Does not support SSL/HTTPS connections - this likely implies that there is no way to restrict access down the line
**Resources**
- [Using terraform to host a static s3 website](https://progressivecoder.com/terraform-static-s3-website/)
- [Another guide on terraform to host a s3 website] (https://francescoboffa.com/s3-static-website-terraform/)
- [AWS documentation] (https://docs.aws.amazon.com/AmazonS3/latest/userguide/WebsiteHosting.html)

### GitHub with cloudfront
**Pro**
- This is possible using GitHub pages and cloudfront
- Very simple and does not require an S3 bucket or EC2 instance - also does not require copying data and everything will be in one place
- I'm not sure that this is a pro or a con, but this would be managed as a custom origin in cloudfront (the same as EC2)
**Con**
- Seems to be very little documentation on this, although I did find a few blog posts
- Not super scalable, the amount that you can serve over GitHub pages is limited
**Resources**
- [Medium article on using GitHub pages and cloudfront] (https://medium.com/@bschandu67/host-your-website-using-github-pages-aws-route53-and-aws-cloudfront-7345493d2ea6)
- [Article on moving from pages to s3 with a little bit of discussion of advantages of s3 with cloudfront] (https://edunham.net/2015/06/25/moving_a_jekyll_site_from_github_pages_to_amazon_s3.html)

### EC2 with cloudfront
- After looking into it more I don't think this is the right option so I'm not going to go into depth.  This would be treated the same in cloudfront as GitHub pages and is more complicated.  The only benefit over using EC2 would be that everything would be managed with Terraform in AWS, but we would still need to copy everything from GitHub so I don't think that this is a real benefit over GitHub pages.

### S3 with cloudfront
**Pro**
- Significantly more documentation than GitHub pages with cloudfront
- allows for more security using signed urls (as opposed to s3 by itself)
**Con**
- More complicated than GitHub pages with cloudfront
- requires copying data from GitHub to the s3 bucket (though this can be managed automatically I think)
**Resources**
- [Deploying static website to s3 and cloudfront using github actions](https://medium.com/swlh/deploying-a-static-website-to-s3-and-cloudfront-using-github-actions-2b00522e43f3)
- [Guide on using CDN for s3 site](https://capgemini.github.io/development/Using-AWS-CloudFront-as-a-CDN-for-an-S3-Static-Site/)

### Summary
**Security:** If we care about security, s3 by itself is not an option.  If we want maximum security then s3 with cloudfront is the best bet, but we can restrict access with any origin server and cloudfront
**Simplicity**: The most simple option is either GitHub pages + cloudfront or s3 by itself.  
**Scalability**: S3 in some capacity is probably the most scalable.  We could start out with s3 by itself for now and if we later decide to set up cloudfront it would be easy to add it on. s3 also has unlimited storage and more documentation than GitHub pages so it will be easier to determine best practices.
**Latency**: The magnitude of difference in latencies really depends on where users are located. I found a mini-experiment someone did on Quora, and it looks like for the US, cloudfront only really improves latencies by ~20ms.  However, when connecting from EU there's ~100ms improvement, and APAC connections see ~150ms improvement.  I don't see this being a big issue for us for now.
**Cost**: I think all of the options have relatively similar costs, with those involving s3 being slightly more expensive.  S3 costs $0.03 per GB. GitHub pages is free for public repositories.  CloudFront is free for the 1TB of data transfer and 10,000,000 HTTP(S) requests per month.  After that, data transfers are free when fetching from S3 or EC2 and would depend on regions and is tiered based on usage but seems to be relatively inexpensive. More info on pricing is [here](https://aws.amazon.com/cloudfront/pricing/)
**Recommendation:** For now, I think we should either do s3 by itself or GitHub pages + cloudfront.  S3 by itself would allow us the ability to later convert to cloudfront if latency and security become an issue.  GitHub pages would handle security and latency issues now. However, I don't think latency will be a huge issue for us now, though down the line it could become problematic if we are running a large number of international experiments.  That being said, s3 by itself now would allow us to later on convert to cloudfront easily if we run into these issues.

**Comment by JamesPHoughton** [comment]
It sounds like a good solution, for now, would be to use S3 by itself with the possibility to add cloudfront down the road if we need it to either access control resources or improve latency. This is basically what we're currently doing with the public S3 bucket that we used when testing the video coding tool. If all we really need is for it to serve files, then we don't even need to set it up as a "website" per se.

Maybe the first step is just to create a publicly viewable S3 bucket for the cdn content and get it to mirror the deliberation-assets repo. That may be enough on its own, and then maybe we just point a subdomain at it. 

The next thing to research is probably the best way to get the S3 bucket to mirror the deliberation-assets repo, and stay up to date with it.

**Comment by kepstein23** [comment]
I found an [open-source workflow](https://github.com/peter-evans/s3-backup) on GitHub that accomplishes this. I've drafted up what is essentially a copy of this, but I don't think I have permission to set secrets in the repo.  @JamesPHoughton Is it possible to give me access to this?  We'll need to give the repo the AWS access key and secret.

**Comment by kepstein23** [comment]
Also, I am working on setting up a terraform workspace for deliberation-assets in deliberation-infrastructure.  For now all this will do is make an s3 bucket and point a subdomain at it, but it'll be nice to have the infrastructure in place when we likely add cloudfront later down the line.  Following [AWS naming conventions](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html), I'm planning on calling it "_deliberation-assets_"

**Comment by JamesPHoughton** [comment]
That sounds right.

**Comment by JamesPHoughton** [comment]
Once we have this set up, we'll need to:
- [ ] make some changes to `deliberation empirica` to point to the correct CDN root URL
- [ ] Check that CORS policy is set properly
- [ ] spot check CDN access from locally hosted experiment
- [ ] spot check CDN access from experiment on production server
- [ ] take down the CDN server on digitalocean

**Comment by kepstein23** [comment]
Update: GitHub actions has been set up in this repo so that the s3 bucket mirrors main exactly.  I think assets.deliberation-lab.org is set up to point at the bucket, but I'm not really sure that's configured correctly - when you visit assets.deliberation-lab.org, you get a "This site cannot be reached" error but that might just be because we don't have anything to display.

**Comment by JamesPHoughton** [comment]
Here's a quick test showing we can access the CDN publicly:

If the CDN is working, this should render the experiment lifecycle image:
![Title text for the lifecycle image](http://assets.deliberation-lab.org/shared/lifecycle.png)
